### ISSUE TITLE
Brew hardcoded version look up

### ISSUE THREAD

**Issue by jack-steer** [jack-steer/create-sdl-app#1]
When the application starts up, it checks to see if SDL is installed via brew. The app looks for a specific version (2.28.5).

We'll want to make this dynamic so regardless of the version installed, the application can find the version. This would include the folders and the necessary files.

**Comment by dhe10-sbg** [comment]
Hey Jack 👋 Im interested in supporting with this issue

**Comment by Disc0des** [comment]
Hey Jack 👋 Im interested in supporting with this issue

**Comment by jack-steer** [comment]
Hey @Disc0des that would be great thanks, no one currently assigned to this.

**Comment by Disc0des** [comment]
Can you add me as a Collab so I can branch/PR ?

**Comment by jack-steer** [comment]
Sent an invite to collab now 👍
